application: ryanslootpy
version: 1
runtime: python27
api_version: 1
threadsafe: true

inbound_services:
- mail

handlers:
- url: /stylesheets
  static_dir: stylesheets

- url: /styles
  static_dir: styles

- url: /js
  static_dir: js

- url: /images
  static_dir: images

- url: /favicon.ico
  static_dir: images/favicons

- url: /_ah/mail/.+
  script: inboundmail.application
  login: admin
  secure: always

- url: /d3try
  script: strike.application
  secure: always

- url: /tasks/nytimes
  script: nytimes.application
  secure: always
  login: admin

- url: /failedconnection
  script: blog.application
  secure: always

- url: /watchlist
  script: watchlist.application
  secure: always

- url: /strike/.*
  script: profile.application
  secure: always

- url: /openingday
  script: openingday.application
  secure: always

- url: /news
  script: news.application
  secure: always

- url: /wikilist
  script: listofallwikis.application
  secure: always

- url: /.*
  script: urls.application
  secure: always

libraries:
- name: jinja2
  version: latest
